# Auto-generated by InfraPilot
terraform {
  backend "s3" {
    bucket = "terraform-state"
    key    = "infrapilot/terraform.tfstate"
    region = "us-east-1"

    endpoints = {
      s3 = "http://localhost:4566"
    }

    access_key                  = "test"
    secret_key                  = "test"
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_requesting_account_id  = true
    force_path_style            = true
  }
}

# Antes de rodar terraform init, crie o bucket no LocalStack:
# aws --endpoint-url=http://localhost:4566 s3 mb s3://terraform-state

provider "aws" {
  region                      = var.aws_region
  access_key                  = "test"
  secret_key                  = "test"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    ec2            = "http://localhost:4566"
    s3             = "http://localhost:4566"
    rds            = "http://localhost:4566"
    iam            = "http://localhost:4566"
    lambda         = "http://localhost:4566"
    dynamodb       = "http://localhost:4566"
    sqs            = "http://localhost:4566"
    sns            = "http://localhost:4566"
    kinesis        = "http://localhost:4566"
    cloudwatch     = "http://localhost:4566"
    cloudwatchlogs = "http://localhost:4566"
    route53        = "http://localhost:4566"
    apigateway     = "http://localhost:4566"
    eks            = "http://localhost:4566"
    elb            = "http://localhost:4566"
    elbv2          = "http://localhost:4566"
  }
}

# Workspaces:
#   terraform workspace new dev
#   terraform workspace new tst
#   terraform workspace new prd
#   terraform workspace select dev   # então: terraform plan -var-file=dev.tfvars

module "v1" {
  source = "./modules/v1"
  name                 = "${terraform.workspace}-vpc_principal"
  cidr_block           = "10.0.0.0/16"
  enable_dns_support   = true
  enable_dns_hostnames = true
  instance_tenancy     = "default"
  environment          = terraform.workspace
}

module "sn_pub_1" {
  source = "./modules/sn_pub_1"
  name                    = "${terraform.workspace}-subnet_public_1"
  vpc_id                  = module.v1.vpc_id
  cidr_block              = "10.0.1.0/24"
  map_public_ip_on_launch = false
  environment             = terraform.workspace
}

module "igw1" {
  source = "./modules/igw1"
  name        = "${terraform.workspace}-igw_main"
  vpc_id      = module.v1.vpc_id
  environment = terraform.workspace
}

module "ec1" {
  source = "./modules/ec1"
  name                   = "${terraform.workspace}-ec2_server"
  ami                    = "ami-0c02fb55956c7d316"
  instance_type          = "t3.micro"
  subnet_id              = module.sn_pub_1.subnet_id
  tenancy                = "default"
  monitoring             = false
  termination_protection = false
  root_volume_size       = 20
  root_volume_type       = "gp3"
  root_volume_encrypted  = false
  use_spot               = var.use_spot
  environment            = terraform.workspace
  vpc_security_group_ids = [module.sg_web.sg_id]
}

module "db1" {
  source = "./modules/db1"
  name                    = "${terraform.workspace}-rds_mysql"
  engine                  = "mysql"
  engine_version          = "8.0"
  instance_class          = "db.t3.micro"
  username                = "admin"
  allocated_storage       = 20
  storage_type            = "gp3"
  multi_az                = var.multi_az
  backup_retention_period = 7
  deletion_protection     = false
  environment             = terraform.workspace
  vpc_security_group_ids = [module.sg_db.sg_id]
}

module "sg_web" {
  source = "./modules/sg_web"
  name           = "${terraform.workspace}-sg_web"
  sg_description = "Managed by InfraPilot"
  vpc_id         = module.v1.vpc_id
  environment    = terraform.workspace
  ingress_rules = [
    { from_port = 80, to_port = 80, protocol = "tcp", cidr = "0.0.0.0/0", description = "HTTP" },
    { from_port = 443, to_port = 443, protocol = "tcp", cidr = "0.0.0.0/0", description = "HTTPS" }
  ]
  egress_rules  = [
    { from_port = 0, to_port = 0, protocol = "-1", cidr = "0.0.0.0/0", description = "All outbound" }
  ]
}

module "sg_db" {
  source = "./modules/sg_db"
  name           = "${terraform.workspace}-sg_db"
  sg_description = "Managed by InfraPilot"
  vpc_id         = module.v1.vpc_id
  environment    = terraform.workspace
  ingress_rules = [
    { from_port = 3306, to_port = 3306, protocol = "tcp", cidr = "10.0.0.0/8", description = "mysql from private network" }
  ]
  egress_rules  = [
    { from_port = 0, to_port = 0, protocol = "-1", cidr = "0.0.0.0/0", description = "All outbound" }
  ]
}

module "cw1" {
  source = "./modules/cw1"
  name               = "${terraform.workspace}-cloudwatch_monitoring"
  alarm_namespace    = "AWS/EC2"
  alarm_metric       = "CPUUtilization"
  alarm_threshold    = 80
  alarm_period       = 300
  alarm_eval_periods = 2
  environment        = terraform.workspace
}

